src/config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
     path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('registro/', include('registro.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/core/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    path('register/', views.CustomRegisterView.as_view(), name='register'),
    path('profile/', views.UpdateProfileView.as_view(), name='profile'),
]

src/registro/urls.py
from django.urls import path

from .views import index
from .views_models import categoria, alimento, usuario, consumo

app_name = "registro"

urlpatterns = [path('', index, name='index')]

urlpatterns += [
    path('categoria/list/', categoria.categoria_list, name='categoria_list'),
    path('categoria/create/', categoria.categoria_create, name='categoria_create'),
    path('categoria/update/<int:pk>', categoria.categoria_update, name='categoria_update'),
    path('categoria/detail/<int:pk>', categoria.categoria_detail, name='categoria_detail'),
    path('categoria/delete/<int:pk>', categoria.categoria_delete, name='categoria_delete'),
]

urlpatterns += [
    path('alimento/list/', alimento.AlimentoListView.as_view(), name='alimento_list'),
    path('alimento/create/', alimento.AlimentoCreateView.as_view(), name='alimento_create'),
    path('alimento/update/<int:pk>', alimento.AlimentoUpdateView.as_view(), name='alimento_update'),
    path('alimento/detail/<int:pk>', alimento.AlimentoDetailView.as_view(), name='alimento_detail'),
    path('alimento/delete/<int:pk>', alimento.AlimentoDeleteView.as_view(), name='alimento_delete'),
]

urlpatterns += [
    path('usuario/list/', usuario.UsuarioListView.as_view(), name='usuario_list'),
    path('usuario/create/', usuario.UsuarioCreateView.as_view(), name='usuario_create'),
    path('usuario/update/<int:pk>', usuario.UsuarioUpdateView.as_view(), name='usuario_update'),
    path('usuario/detail/<int:pk>', usuario.UsuarioDetailView.as_view(), name='usuario_detail'),
    path('usuario/delete/<int:pk>', usuario.UsuarioDeleteView.as_view(), name='usuario_delete'),
]

urlpatterns += [
    path('consumo/list/', consumo.ConsumoListView.as_view(), name='consumo_list'),
    path('consumo/create/', consumo.ConsumoCreateView.as_view(), name='consumo_create'),
    path('consumo/detail/<int:pk>', consumo.ConsumoDetailView.as_view(), name='consumo_detail'),
]

src/core/forms.py
from typing import Any

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = AuthenticationForm
        fields = ['username', 'password']


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']
        help_texts = {'username': ''}

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

src/core/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_not_required  # type: ignore
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView

from .forms import CustomAuthenticationForm, CustomUserCreationForm, UserProfileForm


@login_not_required
def index(request):
    return render(request, 'core/index.html')


@login_not_required
def about(request):
    return render(request, 'core/about.html')


class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm
    template_name = 'core/login.html'
    next_page = reverse_lazy('core:index')

    def form_valid(self, form: AuthenticationForm) -> HttpResponse:
        usuario = form.get_user()
        messages.success(
            self.request, f'Inicio de sesión exitoso ¡Bienvenido {usuario.username}!'
        )
        return super().form_valid(form)


@method_decorator(login_not_required, name='dispatch')
class CustomRegisterView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'core/register.html'
    success_url = reverse_lazy('core:login')

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        messages.success(self.request, 'Registro exitoso. Ahora puedes iniciar sesión.')
        return super().form_valid(form)


class UpdateProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = 'core/profile.html'
    success_url = reverse_lazy('core:index')

    def get_object(self):
        # Devuelve el usuario actual en lugar de esperar un pk
        return self.request.user

src/core/templates/core/componentes/card.html
<div class="col-md-4 mb-5">
    <div class="card h-100">
        <div class="card-body">
            <h2 class="card-title">{{ titulo }}</h2>
            <p class="card-text">{{ contenido }}</p>
        </div>
        <div class="card-footer"><a class="btn btn-sm" style="background-color:#75be64" href="#!">Más info</a></div>
    </div>
</div>

src/core/templates/core/componentes/footer.html
<footer class="py-2 fixed-bottom bg-success">
    <div class="container px-4 px-lg-5">
        <p class="m-0 text-center text-white">Copyright &copy; Mi sitio hecho por
            Lourdes Ramirez 2024</p>
    </div>
</footer>

src/core/templates/core/componentes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-success" style="background-color: #549d45;">
    <div class="container px-5">
        <a class="navbar-brand" href="{% url 'core:index' %}"><i class="fa-solid fa-house"></i> Inicio</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'registro:index' %}">Registros</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:profile' %}">Perfil</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:about' %}">Acerca de mí</a></li>
                <li class="nav-item">
                    <form action="{% url 'core:logout' %}" method="post">
                        {% csrf_token %}
                        <button class="nav-link btn btn-link" type="submit">Logout</button>
                    </form>
                </li>

                {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'core:about' %}">Acerca de mí</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'core:login' %}">Login</a></li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>